### ISSUE TITLE
Use vcs-mx (version:O-2018.09-SP2) run :make hello-world, occurs "Illegal instruction (core 0) at PC 0x000001e8:"

### ISSUE THREAD

**Issue by JmheYouzi** [openhwgroup/core-v-verif#433]
# Template for CORE-V-Verif Issues

## Bug Title
Use vcs-mx (version:O-2018.09-SP2) run :make hello-world, occurs "Illegal instruction (core 0) at PC 0x000001e8:"
### Type
* Confusing or extraneous status or error messages

### Steps to Reproduce
Please provide:
1. URL to branch that exhibits the issue.
 https://github.com/openhwgroup/core-v-verif/tree/master/cv32/sim/uvmt_cv32

2. Command line:  
 make hello-world

3. Logfile and/or wave-dump info (screen shots can be useful)
![1](https://user-images.githubusercontent.com/73106972/101714886-6a40aa80-3ad5-11eb-880e-051caba2c7ee.png)
![2](https://user-images.githubusercontent.com/73106972/101714904-70cf2200-3ad5-11eb-94d2-ddbde0e53df8.png)
![3](https://user-images.githubusercontent.com/73106972/101714911-73ca1280-3ad5-11eb-9889-ec1a1c888c90.png)

### Additional context
    My CentOS version is 6.1, and when I type : make hello-world, it occurs the line " Illegal instruction (core 0) at PC 0x000001e8‘’ ，I want to know how to fix this problem.Thanks for your effort!

**Comment by MikeOpenHWGroup** [comment]
Hi @JmheYouzi, thanks for your interest in core-v-verif.   I suspect your problem is a combination of two things:
1. Your command-line is incorrect.  Please review the `README` in the `uvmt_cv32` directory, especially the [test-programs](https://github.com/openhwgroup/core-v-verif/tree/master/cv32/sim/uvmt_cv32#available-test-programs) section.
2. You must use an approved [Toolchain](https://github.com/openhwgroup/core-v-verif/blob/master/cv32/sim/TOOLCHAIN.md) to compile/link your code.

Let me know if these resolve your issues.

**Comment by JmheYouzi** [comment]
Thank  you very much,I fixed this problem , and  I can move on to leran the UVM environment.
First,this time I use the correct command-line：make test TEST=hello-world
Second, I dowmload the  approved Toolchain and set env in "/etc/profile"
![4](https://user-images.githubusercontent.com/73106972/101759677-db538280-3b14-11eb-8e60-7ebae9e46a66.png)
![5](https://user-images.githubusercontent.com/73106972/101759689-de4e7300-3b14-11eb-970d-c82a95e5f5a0.png)
![6](https://user-images.githubusercontent.com/73106972/101759705-e3132700-3b14-11eb-999c-3f56aa0dc784.png)
