### ISSUE TITLE
vplan review for cv32e40x exceptions

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#795]
### Task Outcome
Updated vplan coverage plan definition for all exceptions in the privileged spec for the CV32E40X.  

### Background information
This review will update the coverage definition using the new ISACOV UVM coverage agent in all CORE-V testbenches.

### Location Information
The updated excel can be fetched from this branch:
https://github.com/strichmo/core-v-verif/blob/strichmo/pr/vplan_isacov_abz_etc/cv32e40x/docs/VerifPlans/Simulation/privileged_spec/CV32E40X_exceptions.xlsx

### Completion Criteria
Vplan meeting is completed.
All action items completed
Vplan definition updated on master branch.

**Comment by silabs-robin** [comment]
Hi. I have some feedback/thoughts/questions.

About coverage:
The items are mostly marked as "Functional Coverage", and I think that is fine.
Apart from _"Exception Priority"_ which is "Test Coverage". Does this mean we will not have e.g. a covergroup for this?

In general:
Should there be an item for branch taken/nontaken? (Because nontaken bad addr doesn't except.)
I really like assertions so I wonder if it is ok that the pass/fail criteria is mostly just "Check against ISS".

Missing items?:
I couldn't see any "misaligned", and there are several: instruction, load, store/amo.
(Not sure atm if the following is 40x or just 40s.)
U-mode ecall?
Instruction parity/checksum fault?
